run:
  timeout: 10m

linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - megacheck
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

linters-settings:
  funlen:
    lines: 70
    statements: 40
  lll:
    line-length: 200
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0

issues:
  exclude-use-default: false
  exclude:
    - should have a package comment, unless it's in another file for this package
  exclude-rules:
    - path: _test\.go
      linters:
        - lll
        - funlen
        - dupl