version: '3'

services:
  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    networks:
      - toggle

  postgres:
    image: postgres:13.2-alpine
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=toggle
    ports:
      - 5432:5432
    networks:
      - toggle

  prometheus:
    image: prom/prometheus:v2.27.1
    ports:
      - 9090:9090
    volumes:
      - ${PWD}/infrastructure/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - toggle

  grafana:
    image: grafana/grafana:7.5.7
    ports:
      - 3000:3000
    volumes:
      - storage:/var/lib/grafana
    networks:
      - toggle

  jaeger:
    image: jaegertracing/all-in-one:1.23
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    networks:
        - toggle

  zookeeper:
    image: 'bitnami/zookeeper:3.7'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'
    networks:
      - toggle

  kafka:
    image: 'bitnami/kafka:2.8.0'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - '9092:9092'
    networks:
      - toggle
    depends_on:
      - zookeeper

  proxy:
    image: toggle-envoy:latest
    ports:
      - 8082:8082
    networks:
      - toggle

  elements:
    image: toggle-elements:latest
    ports:
      - 8085:80
    networks:
      - toggle

volumes:
  storage:

networks:
  toggle:
