{
 "title": "Toggle",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_service!=\"grpc.health.v1.Health\"}[$__rate_interval])) by (grpc_service, grpc_method)",
     "legendFormat": "{{grpc_service}} - {{grpc_method}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "1000 * sum(rate(grpc_server_handling_seconds_sum{grpc_service!=\"grpc.health.v1.Health\"}[$__rate_interval])) by (grpc_service, grpc_method)/ sum(rate(grpc_server_handling_seconds_count{grpc_service!=\"grpc.health.v1.Health\"}[$__rate_interval])) by (grpc_service, grpc_method)",
     "legendFormat": "{{grpc_service}} - {{grpc_method}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_service!=\"grpc.health.v1.Health\",grpc_code!=\"OK\"}[$__rate_interval])) by (grpc_service, grpc_method) / sum(rate(grpc_server_handled_total{grpc_service!=\"grpc.health.v1.Health\"}[$__rate_interval])) by (grpc_service, grpc_method)",
     "legendFormat": "{{grpc_service}} - {{grpc_method}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"toggle\"}"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "1000 * sum(rate(go_gc_duration_seconds_sum{job=\"toggle\"}[$__rate_interval])) by (instance) / sum(rate(go_gc_duration_seconds_count{job=\"toggle\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "OS Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_threads{job=\"toggle\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_code=\"OK\"}[$__rate_interval])) / sum(rate(grpc_server_handled_total[$__rate_interval]))",
     "legendFormat": "Uptime"
    }
   ]
  }
 ]
}