name: Reusable docker related workflow

on:
  workflow_call:
    inputs:
      image:
        description: The name of the image
        required: true
        type: string
      platforms:
        description: Platforms to build the target project
        required: false
        type: string
        default: "linux/amd64, linux/arm64, linux/arm/v7"
      dockerfile:
        description: Path to dockerfile
        required: true
        type: string
      need-go-binary:
        description: Decide if job needs Go binary
        required: false
        type: boolean
        default: false

    secrets:
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_TOKEN:
        required: true

jobs:
  build-push-docker:
    name: Build & push ${{ inputs.image }} image
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Download go binary
        if: ${{ inputs.need-go-binary }}
        uses: actions/download-artifact@v2
        with:
          name: go-binary-toggle-${{ github.sha }}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push ${{ inputs.image }}
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ${{ inputs.dockerfile }}
          platforms: ${{ inputs.platforms }}
          push: true
          tags: |
            docker.io/${{ github.repository_owner }}/${{ inputs.image }}:${{ github.sha }}
            docker.io/${{ github.repository_owner }}/${{ inputs.image }}:latest
